name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://lastfm-iceberg.dawdle.space/
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Upload to Dawdle
        uses: dawdlespace/action@176fc01a848b192f009f2f8fa0f022995b825545 # v1.0.0
        with:
          site-id: tqtw6epn9q
          api-key: ${{ secrets.DAWDLE_API_KEY }}
          path: public
          replace: true
